### ISSUE TITLE
Need AdminClientConfig in KafkaOptions

### ISSUE THREAD

**Issue by SuperTroye** [jbendson/SignalR.Kafka#1]
I noticed your project when I needed a SignalR scaleout using Kafka. When I go to run it, it fails when trying to create topics in KafkaHubLifetimeManager/InitTopics. Could you add this? I cloned the repo and could do a pull request.

`public class KafkaOptions
{
    [Required]
    public AdminClientConfig AdminConfig { get; set; }`

...

`    private async Task InitTopics(KafkaOptions options, KafkaTopicConfig kafkaTopicConfig)
    {
        using var adminClient = new AdminClientBuilder(options.AdminConfig).Build();`

It fails because the existing options aren't sufficient for the AdminClient (I need to pass security credentials alongside the BootstrapServers).

Great job by the way...

**Comment by jbendson** [comment]
Agreed this is a problem when security is enabled. The proposed solution looks good. I'd like to keep the AdminConfig optional to support case where topics already exist. Thinking it could skip running InitTopics if AdminConfig is not specified at startup.

Please submit a PR with the fix.

**Comment by jbendson** [comment]
Resolved with https://github.com/jbendson/SignalR.Kafka/pull/2
